allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Flutter's template puts every module's build directory under the project root rather than inside the
// module, so `flutter clean` has one place to empty.
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
